---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# remove all variables from the workspace
rm(list = ls(all = TRUE))

#Library
library(mice) #for missing values
library(glmnet) #for LASSO

#load cleaned train and test data
setwd("/Users/jerem/Downloads/STAT 440/Module 1/stat440module1-master/data")
train <- read.csv("level2.csv", sep=",")
test <- read.csv("test_level2.csv", sep=",")
```

```{r}
#calculate % of missing value for each column
pMiss <- function(x){sum(is.na(x))/length(x)*100}
apply(train,2,pMiss)
#there are some missing values in "confirmed" (0.46%) and "clean_age" (0.91%) in train data
apply(test,2,pMiss)
#there are some missing values in "clean_age" (2%) in test data
```

```{r}
#impute missing numerical values (clean_age) using Predictive Mean Matching method in MICE
temp.num.train <- mice(train,m=5,maxit=50,meth='pmm',seed=500)
train.complete.num <- complete(temp.num.train,1)
temp.test <- mice(test,m=5,maxit=50,meth='pmm',seed=500)
test.complete <- complete(temp.test,1)
apply(train.complete.num,2,pMiss) #still have missing value in "confirmed" in train data
apply(test.complete,2,pMiss) #no more missing values in test data
```

```{r}
#impute missing factors values (date) in train data
train.complete.num$confirmed = as.factor(train.complete.num$confirmed)
test.complete$confirmed = as.factor(test.complete$confirmed)

temp.fac.train <- mice(train.complete.num,m=1,maxit=50,meth='polyreg',seed=500)
train.complete<- complete(temp.fac.train,1)
apply(train.complete,2,pMiss) #no more missing values in train data
```

```{r}
#Predict duration using LASSO
y.1.cv <- train.complete$duration
x.1.cv <- data.matrix(train.complete[,c(-9,-1,-2)]) #Excluding duration, X, age
y.2.cv <- test.complete$duration
x.2.cv <- data.matrix(test.complete[,c(-9,-1,-2)]) #Excluding duration, X, age
cv.lasso.2 <- cv.glmnet(y=y.1.cv, x= x.1.cv, family="gaussian")
pred.las1.min <- predict(cv.lasso.2, newx=x.2.cv, s=cv.lasso.2$lambda.min)
```

```{r}
#Create baseline
baseline = as.data.frame(cbind(test$X, pred.las1.min))
colnames(baseline)[1:2] <-c("Id","duration")
baseline

#Export baseline to txt.
write.table(baseline, file = "/Users/jerem/Downloads/STAT 440/Module 1/baseline_lvl_2_lambda-min.txt", sep = ",",
            row.names = FALSE)
```

