---
title: "STAT 440 using Ridge Regression"
author: "Nathania Santoso"
date: "10/13/2020"
output: html_document
---

```{r}
library(plyr)
library(readr)
library(caret)
library(ggplot2)
library(repr)
library(glmnet)
library(tidyverse)
```

```{r}
setwd("/Users/nathaniasantoso/Desktop")
#load cleaned train and test data
train <- read.csv("level2.csv", sep=",")
test <- read.csv("test_level2.csv", sep=",")
#change the value from T/F to 0 and 1
train[,11:40] <- (train[,11:40])*1
test[,11:40] <- (test[,11:40])*1
#train[,7:10] <- (train[,7:10])*1
#test[,7:10] <- (test[,7:10])*1
#test <- select (test,-c(age))
#train <- select (train,-c(age))
#drop  missing values
#train <- train[complete.cases(train), ]
#test <- test[complete.cases(train), ]
```
#using MICE package for missing data (Training Set)
```{r}
library(mice)
library(VIM)
#see missing data pattern
print(md.pattern(train))
mice_plot <- aggr(train, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(train), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
```
```{r}
print(md.pattern(test))
mice_plot <- aggr(test, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(train), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
```

```{r}
tempData_train <- mice(train,m=1,maxit=50,meth='pmm',seed=500)
summary(tempData_train)
#check the inputed data
tempData_train$imp$clean_age
```


```{r}
tempData_test <- mice(test,m=1,maxit=50,meth='pmm',seed=500)
summary(tempData_test)
#check the inputed data
tempData_test$imp$clean_age
```

```{r}
test <- complete(tempData_test)
completeTrain <- complete(tempData_train)
```



```{r}
#impute missing factors values (date) in train data
completeTrain$dataset <- 1
test$dataset <- 0
combined <- rbind(completeTrain, test)
combined$confirmed = as.factor(combined$confirmed)
combined$clean_age = as.factor(combined$clean_age)
temp_duration <- combined$duration
combined$duration <- NULL
combined <- mice(combined,m=1,maxit=50,meth='pmm',seed=500)
combined$imp$confirmed
combined$imp$clean_age
combined<- complete(combined)
```


```{r}
combined <- cbind(combined, temp_duration)
finalTrain <- subset(combined, dataset == 1)
finalTest <- subset(combined, dataset == 0)
```


```{r}
mice_plot <- aggr(finalTrain, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(train), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
```

```{r}
mice_plot <- aggr(finalTest, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(train), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
```

```{r}
y_train = finalTrain$temp_duration
x = finalTrain %>% select(-temp_duration) %>% data.matrix()
x_test = finalTest %>% select(-temp_duration) %>% data.matrix()
```

#Ridge Regression
```{r}

lambdas <- 10^seq(2, -3, by = -.1)
ridge_reg = glmnet(x, y_train, nlambda = 25, alpha = 0, family='gaussian',lambda=lambdas)   

summary(ridge_reg)
```
#finding the optimal Lambda
```{r}
cv_ridge <- cv.glmnet(x, y_train, alpha = 0, lambda = lambdas)
optimal_lambda <- cv_ridge$lambda.min
optimal_lambda

# Compute R^2 from true and predicted values
eval_results <- function(true, predicted, df) {
  SSE <- sum((predicted - true)^2)
  SST <- sum((true - mean(true))^2)
  R_square <- 1 - SSE / SST
  RMSE = sqrt(SSE/nrow(df))

  
# Model performance metrics
data.frame(
  RMSE = RMSE,
  Rsquare = R_square
)
  
}

# Prediction and evaluation on train data
predictions_train <- predict(ridge_reg, s = optimal_lambda, newx = x)
eval_results(y_train, predictions_train, finalTrain)

# Prediction and evaluation on test data
predictions_test <- predict(ridge_reg, s = optimal_lambda, newx = x_test)
```



```{r}
#create baseline file
baseline <- cbind(test$X,predictions_test)
#rename columns
colnames(baseline)[1:2] <-c("Id","duration")
#export to csv file
write.csv(baseline, file = "baseline.txt",
            row.names = FALSE)
```
