---
title: "Random Forest (Module 1)"
author: "Nathania Santoso"
date: "9/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(plyr)
library(readr)
library(caret)
library(ggplot2)
library(repr)
library(glmnet)
library(tidyverse)
```

```{r}
#setwd("/Users/nathaniasantoso/Desktop")
#load cleaned train and test data
train <- read.csv("data/level3.csv", sep=",")
test <- read.csv("data/test_level3.csv", sep=",")
#change the value from T/F to 0 and 1
#train[,11:40] <- (train[,11:40])*1
#test[,11:40] <- (test[,11:40])*1
train[,11:18] <- (train[,11:18])*1
test[,11:18] <- (test[,11:18])*1
test <- select (test,-c(age))
train <- select (train,-c(age))
#drop  missing values
#train <- train[complete.cases(train), ]
#test <- test[complete.cases(train), ]
```
#using MICE package for missing data (Training Set)
```{r}
library(mice)
library(VIM)
#see missing data pattern
print(md.pattern(train))
mice_plot <- aggr(train, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(train), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
```
```{r}
print(md.pattern(test))
mice_plot <- aggr(test, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(train), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
```

```{r}
tempData_train <- mice(train,m=1,maxit=50,meth='pmm',seed=500)
summary(tempData_train)
#check the inputed data
tempData_train$imp$clean_age
```


```{r}
tempData_test <- mice(test,m=1,maxit=50,meth='pmm',seed=500)
summary(tempData_test)
#check the inputed data
tempData_test$imp$clean_age
```

```{r}
test <- complete(tempData_test)
completeTrain <- complete(tempData_train)
```



```{r}
#impute missing factors values (date) in train data
completeTrain$dataset <- 1
test$dataset <- 0
combined <- rbind(completeTrain, test)

combined$confirmed = as.factor(combined$confirmed)
combined$clean_age = as.factor(combined$clean_age)

temp_duration <- combined$duration
combined$duration <- NULL


combined <- mice(combined,m=1,maxit=50,meth='polyreg',seed=500)
combined$imp$confirmed
combined$imp$clean_age
combined<- complete(combined)
```


```{r}
combined <- cbind(combined, temp_duration)
finalTrain <- subset(combined, dataset == 1)
finalTest <- subset(combined, dataset == 0)
```


```{r}
mice_plot <- aggr(finalTrain, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(train), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
```

```{r}
mice_plot <- aggr(finalTest, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(train), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
```

```{r}
y_train = finalTrain$temp_duration
```

```{r}
#create a random forest model
library(randomForest)
model1 <- randomForest(temp_duration ~ ., data = finalTrain, importance = TRUE)
model1

#create another model with by adding more split
model2 <- randomForest(temp_duration ~ ., data = finalTrain,ntree = 400, mtry = 6, importance = TRUE)
model2
```

```{r}
#see the importance of each variable
varImpPlot(model2) 
#based on the graph of the importance of each variables,I decided to omit some variables
#and only take confirmed, clean_age, cough, sore.throat, city, province, fever (since those are more important based on the graph)
```

```{r}
library(randomForest)
#build another model with just important variables
#model3 <- randomForest(duration ~ confirmed+V1+clean_age+cough+sore.throat+city+province+fever+high.fever, data = completeTrain, ntree = 200, mtry = 6, importance = TRUE)
#model3
#the mean squared of residuals decreased when using just the important variable
model3 <- randomForest(temp_duration ~ respiratory+confirmed+province+V1+clean_age, data = finalTrain, ntree = 200, mtry = 6, importance = TRUE)
model3
```

```{r}
# Compute R^2 from true and predicted values
eval_results <- function(true, predicted, df) {
  SSE <- sum((predicted - true)^2)
  SST <- sum((true - mean(true))^2)
  R_square <- 1 - SSE / SST
  RMSE = sqrt(SSE/nrow(df))

  
# Model performance metrics
data.frame(
  RMSE = RMSE,
  Rsquare = R_square
)
  
}


# Make predictions on training set
predictions_train <- predict(model3, finalTrain)
eval_results(y_train, predictions_train, finalTrain) 

# Make predictions on test set
predictions_test <- predict(model3, finalTest)
```

```{r}
#create baseline file
baseline <- cbind(test$X,predictions_test)
#rename columns
colnames(baseline)[1:2] <-c("Id","duration")
#export to csv file
write.csv(baseline, file = "data/baseline.txt",
            row.names = FALSE)
```
